
title:            Sysco Middleware
subtitle:         data integration
description:      Data Integration, Open-Source, Oracle
disqus_shortname: syscomiddlewareblog
reading_time:     true
words_per_minute: 200

url: //blog.sysco.no
host: 0.0.0.0
port: 4000
baseurl: ""

# Owner
owner:
  name:         Sysco Middleware
  url:          https://sysco.no
  email:        info@sysco.no

# Authors
authors:
  jeroenrinzema:
    name: Jeroen Rinzema
    avatar: /images/avatars/jeroenrinzema.jpg
  catoaune:
    name: Cato Aune
    twitter: catoaune
    avatar: /images/avatars/catoaune.jpg
  jphjulstad:
    name: Jon Petter Hjulstad
    twitter: jphjulstad
    avatar: /images/avatars/jphjulstad.jpg
  jeqo:
    name: Jorge Quilcate
    twitter: jeqo89
    avatar: /images/avatars/jeqo.jpg
  pah:
    name: Paal Holmen
    twitter: paalholmen
    avatar: /images/avatars/pah.jpg
  tisaksen:
    name: Thomas Isaksen
    twitter: tisaksen
    avatar: /images/avatars/catoaune.jpg
  raul:
    name: Raul Castillo
    avatar: /images/avatars/raul.jpg
  oleg:
    name: Oleg Bezemchuk
    avatar: /images/avatars/oleg.jpg
  cliops:
    name: Chris Laurente
    twitter: Cliops
    avatar: /images/avatars/cliops.jpg
  dalibor:
    name: Dalibor Blazevic
    twitter: cubeprogramming
    avatar: /images/avatars/dalibor.jpg
  olveslind:
    name: Olve Slind
    twitter: olveslind
    avatar: /images/avatars/olveslind.jpg
  kolinnebo:
    name: Knut Olav Linnebo
    avatar: /images/avatars/kolinnebo.jpg
  gugalnikov:
    name: Arturo Viveros
    avatar: /images/avatars/gugalnikov.jpg
  kresimirjuric:
    name: Kresimir Juric
    avatar: /images/avatars/kresimirjuric.jpg
  trygveiversland:
    name: Trygve Iversland
    avatar: /images/avatars/trygveiversland.jpg
  sergei-ko:
    name: Sergei Kosolapov
    avatar: /images/avatars/sergei-ko.jpg
  denzza:
    name: Denis Velagic
    avatar: /images/avatars/denzza.jpg
  NikitaZhevnitskiy:
    name: Nikita Zhevnitskiy
    avatar: /images/avatars/NikitaZhevnitskiy.jpg
  PrakharSrivastav:
    name: Prakhar Srivastav
    avatar: /images/avatars/prakhar.png
  TimurSamkharadze:
    name: Timur Samkharadze
    avatar: /images/avatars/timsamkharadze.jpg
  MarijanaJuric:
    name: Marijana Juric Fraculj
    avatar: /images/avatars/marijanajuricfraculj.png

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:categories/:title/
paginate:       7
